name: Weight Difference Report

on:
  pull_request:
    paths:
        - 'runtime/moonbase/src/weights/**/*.rs'
        - 'runtime/moonbase/src/weights/*.rs'
        - 'runtime/moonriver/src/weights/**/*.rs'
        - 'runtime/moonriver/src/weights/*.rs'
        - 'runtime/moonbeam/src/weights/**/*.rs'
        - 'runtime/moonbeam/src/weights/*.rs'


jobs:
    weight-diff:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install subweight
              run: cargo install subweight

            - name: Get changed files
              id: changed-files-yaml
              uses: tj-actions/changed-files@v45
              with:
                files_yaml: |
                    moonbase:
                    - 'runtime/moonbase/src/weights/**'
                    moonriver:
                    - 'runtime/moonriver/src/weights/**'
                    moonbeam:
                    - 'runtime/moonbeam/src/weights/**'
                files_ignore_yaml: |
                    moonbase:
                    - 'runtime/moonbase/src/weights/mod.rs'
                    - 'runtime/moonbase/src/weights/db/mod.rs'
                    moonriver:
                    - 'runtime/moonriver/src/weights/mod.rs'
                    - 'runtime/moonriver/src/weights/db/mod.rs'
                    moonbeam:
                    - 'runtime/moonbeam/src/weights/mod.rs'
                    - 'runtime/moonbeam/src/weights/db/mod.rs'

            - name: Moonbase Weight Difference Data
              if: steps.changed-files-yaml.outputs.moonbase_any_changed == 'true'
              env:
                ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.moonbase_all_changed_files }}
              run: |
                echo "## Moonbase Weight Difference Files" >> weight_diff_report.md
                for file in ${ALL_CHANGED_FILES}; do
                  echo $file >> weight_diff_report.md
                done

                echo "## Moonbase Weight Difference Reports" >> weight_diff_report.md
                for file in ${ALL_CHANGED_FILES}; do
                  subweight compare commits --threshold 1 --strip-path-prefix ".*/" --format csv --no-color --method exact-worst --path-pattern $file ${{github.base_ref}} ${{github.head_ref}} | sed 1,1d | sed '$d' >> weight_diff_report.md
                done
                for file in ${ALL_CHANGED_FILES}; do
                  subweight compare commits --threshold 1 --strip-path-prefix ".*/" --format csv --no-color --method exact-worst --path-pattern $file ${{github.base_ref}} ${{github.head_ref}} | sed 1,1d | sed '$d' >> moonbase_diffs.csv
                done

                echo "## Moonbase Weight Difference JSON" >> weight_diff_report.md
                jq -R 'split(",") | {File: .[0], Extrinsic: .[1], Old: .[2], New: .[3], "Change Percent": (.[4] | tonumber)}' moonbase_diffs.csv | jq -s '.' >> weight_diff_report.md
                jq -R 'split(",") | {File: .[0], Extrinsic: .[1], Old: .[2], New: .[3], "Change Percent": (.[4] | tonumber)}' moonbase_diffs.csv | jq -s '.' > moonbase_diffs.json

                echo "## Moonbase Weight Difference Sorted JSON" >> weight_diff_report.md
                jq 'sort_by(.["Change Percent"] | abs)' moonbase_diffs.json >> weight_diff_report.md
                jq 'sort_by(.["Change Percent"] | abs)' moonbase_diffs.json > moonbase_diffs_sorted.json
            - name: Find Comment
              uses: peter-evans/find-comment@v3
              id: fc
              with:
                issue-number: ${{ github.event.pull_request.number }}
                comment-author: "github-actions[bot]"
                body-includes: "Weight Difference Report"

            - name: Create or update comment
              uses: peter-evans/create-or-update-comment@v4
              with:
                comment-id: ${{ steps.fc.outputs.comment-id }}
                issue-number: ${{ github.event.pull_request.number }}
                body-path: weight_diff_report.md
                edit-mode: replace